name: diffpepbuilder
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - cryptography=41.0.3=py39hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=10.2.89=h713d32c_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib_resources=6.1.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.16.1=pyh0d859eb_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py39hf3d152e_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.0.34=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.4.52=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.7.2=py39h06a4308_0
  - matplotlib-base=3.7.2=py39h1128e8f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.0=py39h5f9d8c6_0
  - numpy-base=1.26.0=py39hb5e798b_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openmm=8.0.0=py39h31b9435_1
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py39h1128e8f_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py39ha6cbd5a_0
  - pip=23.3=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h955ad1f_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=2.1.0=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.0=py39h6a678d5_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - setuptools=68.0.0=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=2.1.0=py39_cu118
  - torchtriton=2.1.0=py39
  - torchvision=0.16.0=py39_cu118
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.12.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py39h06a4308_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - biopython==1.81
      - biotite==0.38.0
      - click==8.1.7
      - contextlib2==21.6.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - easydict==1.11
      - fair-esm==2.0.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gputil==1.4.0
      - hydra-core==1.3.2
      - hydra-joblib-launcher==1.2.0
      - joblib==1.3.2
      - mdtraj==1.9.9
      - ml-collections==0.1.1
      - msgpack==1.0.7
      - omegaconf==2.3.0
      - pathtools==0.1.2
      - protobuf==4.24.4
      - psutil==5.9.6
      - pyparsing==3.1.1
      - pyrootutils==1.0.4
      - python-dotenv==1.0.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soupsieve==2.5
      - svgwrite==1.4.3
      - threadpoolctl==3.2.0
      - tmtools==0.0.3
      - tqdm==4.66.1
      - wandb==0.15.12
      - wget==3.2
